export const enum CONSOLE_METHODS {
  LOG = 'log',
  ERROR = 'error',
  WARN = 'warn',
  DEBUG = 'debug',
}
export const enum LOG_METHODS {
  LOG = 'LOG',
  ERROR = 'ERROR',
  WARN = 'WARN',
  DEBUG = 'DEBUG',
  VERBOSE = 'VERBOSE',
  REQUEST = 'REQUEST',
}

export const LOG_METHODS_TO_CONSOLE: Record<LOG_METHODS, CONSOLE_METHODS> = {
  LOG: CONSOLE_METHODS.LOG,
  ERROR: CONSOLE_METHODS.ERROR,
  WARN: CONSOLE_METHODS.WARN,
  DEBUG: CONSOLE_METHODS.DEBUG,
  VERBOSE: CONSOLE_METHODS.LOG,
  REQUEST: CONSOLE_METHODS.LOG,
};
