version: '3'

services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
